.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CAPR" "1" "November 2010" "Simon Menke" "Capricorn 3.0.0"
.
.SH "NAME"
\fBcapr\fR \- the capricorn client
.
.SH "SYNOPSIS"
\fBcapr\fR \fBping\fR \fB\-\-node\fR=\fIHOSTNAME\fR \fIREPO\fR \fIBRANCHES\fR\.\.\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-node\fR=\fIHOSTNAME\fR
The node to contact\.
.
.SH "COMMANDS"
\fBping\fR
.
.br
Send a ping to be forwarded to all known nodes\.
.
.SH "SEE ALSO"
capricorn(7), caprd(1)
