.\" generated with Ronn/v0.7.0
.\" http://github.com/rtomayko/ronn/tree/0.7.0
.
.TH "CAPRICORN" "7" "June 2010" "Simon Menke" "Capricorn 2.0.8"
.
.SH "NAME"
\fBcapricorn\fR \- semi automatic deployment of rails applications
.
.SH "INSTALL"
Install with Rubygems:
.
.IP "" 4
.
.nf

$ [sudo] gem install capricorn
$ capricornd cluster start
.
.fi
.
.IP "" 0

