.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CAPRICORN" "7" "October 2010" "Simon Menke" "Capricorn 2.0.11"
.
.SH "NAME"
\fBcapricorn\fR \- semi automatic deployment of rails applications
.
.SH "INSTALL"
Install with Rubygems:
.
.IP "" 4
.
.nf

$ [sudo] gem install capricorn
$ capricornd cluster start
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
capricornctl(1) \fIcapricornctl\.1\fR, capricornd(1) \fIcapricornd\.1\fR
