.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "CAPRICORND" "1" "June 2010" "Simon Menke" "Capricorn 2.0.7"
.
.SH "NAME"
\fBcapricornd\fR \- the capricorn server
.
.SH "SYNOPSIS"
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBstart\fR
.
.br
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBstop\fR
.
.br
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBrestart\fR
.
.br
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBreboot\fR
.
.br
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBping\fR
.
.br
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBconsole\fR
.
.br
\fBcapricornd\fR \fBmachine\fR|\fBcluster\fR \fBattach\fR
.
.SH "SEE ALSO"
capricornctl(1) \fIcapricornctl\.1\fR, capricorn(7) \fIcapricorn\.7\fR
